### ISSUE TITLE
Bisq not connecting to bitcoin node on a remote mac

### ISSUE THREAD

**Issue by Quenos** [bisq-network/support#898]
This is probably not a Bisq issue, but I hope you can nonetheless help with it.

I'm running Bisq v1.6.1 on a iMac and that works fine using "use provided bitcoin Core nodes"
I also running a bitcoin core node on a mac Mini in the same local network on address 192.168.0.82
Putting this address in "Use custom Bitcoin Core nodes" and also checking this radio button does not work. The "Bitcoin network peers" stays at 0

The network in itself is working, as I can connect to the mini using the remote desktop

What am I overlooking?

**Comment by jmacxx** [comment]
Check that your node is configured per https://bisq.wiki/Connecting_to_your_own_Bitcoin_node#General_node_settings

**Comment by Quenos** [comment]
I followed the guide and also tried it without Tor, but it is still not connecting

**Comment by Quenos** [comment]
I suspect that the port is somehow closed (?), but on application level there is no firewall and I can't find any documentation as to how open a port in general on MacOs, as UFW would on Linux.

It says (only the parts I think are relevant)
Mar-30 15:17:53.482 [JavaFX Application Thread] INFO  b.c.b.n.LocalBitcoinNode: No local Bitcoin node detected on port 8333. 

Mar-30 15:17:56.971 [ STARTING] INFO  b.c.b.s.WalletConfig: We try to connect to 1 btc nodes

Mar-30 15:17:57.005 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [192.168.0.70]:8333     (0 connected, 1 pending, 1 max) 

Mar-30 15:17:57.233 [NioClientManager] WARN  o.b.n.NioClientManager: Failed to connect with exception: java.net.ConnectException: Connection refused java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:844)

Mar-30 15:17:57.234 [NioClientManager] INFO  o.b.c.PeerGroup: [192.168.0.70]:8333: Peer died      (0 connected, 0 pending, 1 max) 
Mar-30 15:17:57.235 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Peer discovery took 11.51 μs and returned 0 items 
Mar-30 15:17:57.236 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Waiting 1501 ms before next connect attempt to [192.168.0.70]:8333 
Mar-30 15:17:58.740 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [192.168.0.70]:8333     (0 connected, 1 pending, 1 max) 
Mar-30 15:17:58.950 [NioClientManager] WARN  o.b.n.NioClientManager: Failed to connect with exception: java.net.ConnectException: Connection refused java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:844)

Mar-30 15:17:58.950 [NioClientManager] INFO  o.b.c.PeerGroup: [192.168.0.70]:8333: Peer died      (0 connected, 0 pending, 1 max) 
Mar-30 15:17:58.950 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Peer discovery took 2.780 μs and returned 0 items 

etc

**Comment by jmacxx** [comment]
Try simply connecting to your node using `bitcoin-cli` from the machine Bisq runs on, e.g.

`bitcoin-cli -rpcconnect=192.168.0.70 -rpcuser=username -rpcpassword=password getnetworkinfo`

It should also give you a connection refused if its a firewall issue on your mac mini.

I don't know much about Macs but maybe [this](https://apple.stackexchange.com/questions/142778/how-to-open-a-specific-port-in-firewall-os-x-10-9-4#180636) will help.

**Comment by Quenos** [comment]
Not working still.
But I found out it's definitely a port issue. So currently looking for someone who can help me with that.
Thanks for your help narrowing the issue down @jmacxx !

**Comment by pazza83** [comment]
Hi @Quenos has this been resolved?

**Comment by pazza83** [comment]
closing as no response
